DO $$
BEGIN
    CREATE ROLE game;
    EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
    END
$$;

REVOKE ALL PRIVILEGES ON DATABASE postgres FROM game;
DROP USER IF EXISTS game;

CREATE USER game WITH PASSWORD 'game123';

GRANT CONNECT ON DATABASE postgres TO game;
GRANT USAGE ON SCHEMA public TO game;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO game;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO game;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO game;

REVOKE UPDATE (tipo) ON TABLE civil FROM game;
REVOKE UPDATE (tipo) ON TABLE npc FROM game;
REVOKE UPDATE (tipo) ON TABLE item FROM game;
REVOKE UPDATE (tipo) ON TABLE feitico FROM game;